### ISSUE TITLE
Api calls in viewModelScope (Dispatcher.Main)

### ISSUE THREAD

**Issue by iamanbansal** [MindorksOpenSource/Kotlin-Coroutines-Android-Examples#2]
For reference: [ViewModel.kt](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/lifecycle/lifecycle-viewmodel-ktx/src/main/java/androidx/lifecycle/ViewModel.kt)

I see you are using viewModelScope for API calls without switching the context.
viewModelScope uses Dispatcher.Main, so it is not appropriate to directly launch the coroutine. It should be viewModelScope.lauch(Dispatcher.IO){ //api calls }

Please correct me if I'm wrong.
Thanks for the repo.

**Comment by prempalsingh** [comment]
@iamanbansal It's a good practice to write suspend functions in a way that they are safe to call from the main thread. Retrofit uses a custom Dispatcher internally to ensure API calls happen on an IO thread so it doesn't matter what Dispatcher we use.

**Comment by iamanbansal** [comment]
@prempalsingh Oh Okay!! Thanks!!
